apiVersion: v1
kind: Service
metadata:
  name: basicnodeapp-service
spec:
  type: NodePort
  selector:
    app: basicnodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001